name: check

on:
  push:

env:
  CARGO_TERM_COLOR: always
  CC: clang

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Update toolchain
      run: |
        rustup update
        rustup default nightly

    - name: Setup target
      run: rustup target add ${{ matrix.target }}

    - name: Check
      run: cargo check --all --target ${{ matrix.target }}


