name: package

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Cross-compilation target required for your Rust project"
        type: choice
        options:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - all
        required: true

      archive-name:
        type: string
        default: archive

      retention-days:
        description: "Archive retention period you need to set"
        type: number
        default: 1

jobs:
  build-gnu:
    uses: ./.github/workflows/build.yml
    if: ${{ inputs.target == 'all' || inputs.target == 'x86_64-unknown-linux-gnu' }}
    with:
      target: x86_64-unknown-linux-gnu
      archive-name: linux-gnu-archive
      archive-paths: |
        target/x86_64-unknown-linux-gnu/release/pioneer
        target/x86_64-unknown-linux-gnu/release/installer_builder
        target/x86_64-unknown-linux-gnu/release/checker_builder
        configlist.schema.json

  build-musl:
    uses: ./.github/workflows/build.yml
    if: ${{ inputs.target == 'all' || inputs.target == 'x86_64-unknown-linux-musl' }}
    with:
      target: x86_64-unknown-linux-musl
      archive-name: linux-musl-archive
      archive-paths: |
        target/x86_64-unknown-linux-musl/release/pioneer
        target/x86_64-unknown-linux-musl/release/installer_builder
        target/x86_64-unknown-linux-musl/release/checker_builder
        configlist.schema.json

  build-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update toolchain
        run: |
          rustup update
          rustup default nightly

      - name: Setup target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Checker
        run: |
          cargo r --bin checker_builder -- checker

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: checker
          path: checker.sh
          retention-days: 1
